### ISSUE TITLE
Install problem with pip

### ISSUE THREAD

**Issue by taoansf** [NOAA-ORR-ERD/OilLibrary#11]
Hello,

I'm trying to install OilLibrary but I don't know how to solve the error showed below.

_C:\WINDOWS\system32>pip install git+https://github.com/NOAA-ORR-ERD/OilLibrary.git
Collecting git+https://github.com/NOAA-ORR-ERD/OilLibrary.git
  Cloning https://github.com/NOAA-ORR-ERD/OilLibrary.git to c:\users\zoi\appdata\local\temp\pip-9djbzd-build
Installing collected packages: oil-library
  Running setup.py install for oil-library ... error
    Complete output from command c:\opentelemac-mascaret\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\zoi\\appdata\\local\\temp\\pip-9djbzd-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\zoi\appdata\local\temp\pip-shjpeo-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    OilLibrary database generation failed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\zoi\appdata\local\temp\pip-9djbzd-build\setup.py", line 165, in <module>
        zip_safe=False,
      File "c:\opentelemac-mascaret\python27\lib\distutils\core.py", line 152, in setup
        dist.run_commands()
      File "c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\opentelemac-mascaret\python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\opentelemac-mascaret\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\opentelemac-mascaret\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\opentelemac-mascaret\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\opentelemac-mascaret\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\zoi\appdata\local\temp\pip-9djbzd-build\setup.py", line 124, in run
        init_db()
      File "c:\users\zoi\appdata\local\temp\pip-9djbzd-build\setup.py", line 53, in init_db
        import oil_library.initializedb
      File "oil_library\__init__.py", line 13, in <module>
        import sample_oils
      File "oil_library\sample_oils\__init__.py", line 1, in <module>
        import oil_gas
      File "oil_library\sample_oils\oil_gas.py", line 9, in <module>
        'api': uc.convert('Density',
    AttributeError: 'module' object has no attribute 'convert'

    ----------------------------------------
Command "c:\opentelemac-mascaret\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\zoi\\appdata\\local\\temp\\pip-9djbzd-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\zoi\appdata\local\temp\pip-shjpeo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\zoi\appdata\local\temp\pip-9djbzd-build\_

Any help will be welcome

With best regards,

Taoan

**Comment by knutfrode** [comment]
It seems like the requirements are missing.
Did you do this first?
pip install -r requirements.txt


On Dec 8, 2017 16:22, "taoansf" <notifications@github.com> wrote:

Hello,

I'm trying to install OilLibrary but I don't know how to solve the error
showed below.







































*C:\WINDOWS\system32>pip install
git+https://github.com/NOAA-ORR-ERD/OilLibrary.git
<https://github.com/NOAA-ORR-ERD/OilLibrary.git> Collecting
git+https://github.com/NOAA-ORR-ERD/OilLibrary.git
<https://github.com/NOAA-ORR-ERD/OilLibrary.git> Cloning
https://github.com/NOAA-ORR-ERD/OilLibrary.git
<https://github.com/NOAA-ORR-ERD/OilLibrary.git> to
c:\users\zoi\appdata\local\temp\pip-9djbzd-build Installing collected
packages: oil-library Running setup.py install for oil-library ... error
Complete output from command c:\opentelemac-mascaret\python27\python.exe -u
-c "import setuptools,
tokenize;file='c:\users\zoi\appdata\local\temp\pip-9djbzd-build\setup.py';f=getattr(tokenize,
'open', open)(file);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, file, 'exec'))" install --record
c:\users\zoi\appdata\local\temp\pip-shjpeo-record\install-record.txt
--single-version-externally-managed --compile: running install running
build running build_py OilLibrary database generation failed Traceback
(most recent call last): File "", line 1, in File
"c:\users\zoi\appdata\local\temp\pip-9djbzd-build\setup.py", line 165, in
zip_safe=False, File
"c:\opentelemac-mascaret\python27\lib\distutils\core.py", line 152, in
setup dist.run_commands() File
"c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 953, in
run_commands self.run_command(cmd) File
"c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 972, in
run_command cmd_obj.run() File
"c:\opentelemac-mascaret\python27\lib\site-packages\setuptools\command\install.py",
line 61, in run return orig.install.run(self) File
"c:\opentelemac-mascaret\python27\lib\distutils\command\install.py", line
563, in run self.run_command('build') File
"c:\opentelemac-mascaret\python27\lib\distutils\cmd.py", line 326, in
run_command self.distribution.run_command(command) File
"c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 972, in
run_command cmd_obj.run() File
"c:\opentelemac-mascaret\python27\lib\distutils\command\build.py", line
127, in run self.run_command(cmd_name) File
"c:\opentelemac-mascaret\python27\lib\distutils\cmd.py", line 326, in
run_command self.distribution.run_command(command) File
"c:\opentelemac-mascaret\python27\lib\distutils\dist.py", line 972, in
run_command cmd_obj.run() File
"c:\users\zoi\appdata\local\temp\pip-9djbzd-build\setup.py", line 124, in
run init_db() File
"c:\users\zoi\appdata\local\temp\pip-9djbzd-build\setup.py", line 53, in
init_db import oil_library.initializedb File "oil_library_init*.py", line
13, in
import sample_oils
File "oil_library\sample_oils_*init*_.py", line 1, in
import oil_gas
File "oil_library\sample_oils\oil_gas.py", line 9, in
'api': uc.convert('Density',
AttributeError: 'module' object has no attribute 'convert'

----------------------------------------

Command "c:\opentelemac-mascaret\python27\python.exe -u -c "import
setuptools, tokenize;*file*='c:\users\zoi\appdata\local\temp\pip-9djbzd-
build\setup.py';f=getattr(tokenize, 'open',
open)(*file*);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, *file*, 'exec'))" install --record
c:\users\zoi\appdata\local\temp\pip-shjpeo-record\install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in
c:\users\zoi\appdata\local\temp\pip-9djbzd-build_

Any help will be welcome

With best regards,

Taoan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-ORR-ERD/OilLibrary/issues/11>, or mute the thread

**Comment by taoansf** [comment]
Hello,

Yes, some requiriments were missing. However, after install the dependencies the installer continues to stop at with the same error

_File "oil_library\sample_oils\oil_gas.py", line 9, in
'api': uc.convert('Density',
AttributeError: 'module' object has no attribute 'convert'_

**Comment by ChrisBarker-NOAA** [comment]
That's odd.

what version of unit_conversion do you have? It should be 2.5.5:

$ python -c "import unit_conversion; print unit_conversion.__version__"
2.5.5

If you aren't getting it from our conda channel, it is here:

https://github.com/NOAA-ORR-ERD/PyNUCOS/releases

you should be able to install from there with pip:

pip install https://github.com/NOAA-ORR-ERD/PyNUCOS/archive/v2.5.5.tar.gz

Sorry about the inconsistent naming conventions -- I'll clean that up one of these days.

Note that unit_conversion for sure, and maybe others, aren't fully pip installable, so you want to get the dependencies installed first.

Also -- we should probably push a new version to gitHub -- stay tuned.

**Comment by ChrisBarker-NOAA** [comment]
Oh, and you can test unit_conversion after installation with:

pytest --pyargs unit_conversion

**Comment by taoansf** [comment]
Hello,

Yes! my version of unit_conversion was old. 

This comand solve it :)
pip install https://github.com/NOAA-ORR-ERD/PyNUCOS/archive/v2.5.5.tar.gz

Thank you!

**Comment by ChrisBarker-NOAA** [comment]
glad it worked.

-CHB
