### ISSUE TITLE
Dynamical visocities instead of kinematic viscosities

### ISSUE THREAD

**Issue by knutfrode** [NOAA-ORR-ERD/OilLibrary#12]
For the oils stored in [OilLibNorway](https://github.com/NOAA-ORR-ERD/OilLibrary/blob/master/oil_library/OilLibNorway), viscosities are not stored as kinematic values (columns AJ-AZ in the CSV-file) as for the other oils in [OilLib](https://github.com/NOAA-ORR-ERD/OilLibrary/blob/master/oil_library/OilLib), but rather as dynamic viscosities (columns BA-BR)
However, I seem to get a bit too high viscosities for these oils from the OilLibrary:
```
>>>from oil_library import get_oil_props
>>>print get_oil_props('BALDER').kvis_at_temp(286)
```

This gives ```kvis``` of 0.00173 corresponding to ```dvis``` of about 1.58 kg/ms.
However, the measured viscosity is 0.219 kg/ms as given in the table, i.e. an order of magnitude lower.

I also noted that (with ```o=get_oil_props('BALDER')```)
```o.record.imported.dvis``` gives the correct dynamical viscosities as given in the table, whereas ```o.record``` has no property ```dvis```, but only ```kvis```, with the wrong value (0.00173)

**Comment by JamesMakela-NOAA** [comment]
Hello @knutfrode,

The dynamic viscosities are still visible in the oil_props object.  Try this:
```
In [1]: from oil_library import get_oil_props
In [2]: op_obj = get_oil_props('BALDER')

In [3]: op_obj.kvis_at_temp(286)
Out[3]: 0.0017328644035562455  # so this is indeed what we are seeing

In [4]: op_obj.record.imported.dvis
Out[4]: 
[<DVis(0.219 kg/ms at 286.15K)>,
 <DVis(0.394 kg/ms at 286.15K)>,
 <DVis(0.985 kg/ms at 286.15K)>,
 <DVis(1.58 kg/ms at 286.15K)>]
```
The problem that I see, at least for this particular record, is that all the dynamic viscosities are referenced at the same temperature.  I checked the data file and this is indeed the case, and the record needs to be fixed.

If you have the proper reference temperatures for this oil, you can make the change in the data file and reload the database.  In fact, if you would like to submit a PR to fix this record, we would be glad to accept it.

Regards,
James L. Makela

**Comment by knutfrode** [comment]
Hi James, thank you for clarifying.

The viscosities are given for the same temperatures, but for different weathering states (evaporation fraction). 
Here is an example of the table from the orignial report:  ![balder_report_screenshot](https://user-images.githubusercontent.com/5222051/35824710-03932816-0ab4-11e8-8ff9-9a4dbaf66675.png)

and here is how the data are recorded in the OilLibNorway file:
![balder_database](https://user-images.githubusercontent.com/5222051/35824795-49d9c1cc-0ab4-11e8-969d-ba1055f47482.png)
(Viscoities are divided by 1000 by conversion from cP to kg/ms)

I believe the table from the report is supposed to be valid for 13deg Celcius?
Or should we instead use the evaporation temperatures in the header (+150C, +200C, +250C)?

**Comment by ChrisBarker-NOAA** [comment]
Knut-Frode,

If you happen to get this right away, would you like to join me and a
couple folks for Dinner?

Monday evening, 7:00pm or so.

Chris

Sent from my iPhone

On Feb 5, 2018, at 1:44 PM, Knut-Frode Dagestad <notifications@github.com>
wrote:

Hi James, thank you for clarifying.

The viscosities are given for the same temperatures, but for different
weathering states (evaporation fraction).
Here is an example of the table from the orignial report: [image:
balder_report_screenshot]
<https://user-images.githubusercontent.com/5222051/35824710-03932816-0ab4-11e8-8ff9-9a4dbaf66675.png>

and here is how the data are recorded in the OilLibNorway file:
[image: balder_database]
<https://user-images.githubusercontent.com/5222051/35824795-49d9c1cc-0ab4-11e8-969d-ba1055f47482.png>
(Viscoities are divided by 1000 by conversion from cP to kg/ms)

I believe the table from the report is supposed to be valid for 13deg
Celcius?
Or should we instead use the evaporation temperatures in the header (+150C,
+200C, +250C)?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-ORR-ERD/OilLibrary/issues/12#issuecomment-363198920>,
or mute the thread

**Comment by JamesMakela** [comment]
Hello again @knutfrode,

Oh yes, you are of course correct about the different dynamic viscosity records having different weathering amounts.  My mistake there.

The only other thing to check would be the oil's density at 13C.  This is necessary to convert from dynamic to kinematic.  Give me a minute to check it out.

James

**Comment by JamesMakela** [comment]
Ok, this does seem like a bug.  Hand-calculating this, I believe the kinematic viscosity should be about 239.13 cSt, not 1725.2 cSt.

I will need to look into this for a bit.  I will probably have a solution tonight sometime.

**Comment by JamesMakela-NOAA** [comment]
Hello @knutfrode,

Ok, sorry for the delay.  The problem itself was that we were not properly distinguishing the DVis objects by their weathering properties.  Determining this was pretty easy.  But how best to fix it was a bit more difficult.

The fix is in commit f7ffcf4, and it seems to work as I would expect.

```
In [1]: from oil_library import get_oil_props

In [2]: op_obj = get_oil_props('BALDER')

In [3]: op_obj.kvis_at_temp(286)
Out[3]: 0.00024018816732836567
```

Just pull the master branch and you should get it.

**Comment by knutfrode** [comment]
Yes, now it seems correct. Thanks a lot for your efforts!
I noted that viscosities changed a little also for non-Norwegian oils, so hopefully this was a general improvement.

Btw, when I import oil_library I get the following warning:
```
/usr/local/lib/python2.7/dist-packages/scipy/optimize/minpack.py:785: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
```

and when I try ```python setup.py test``` it fails with message:
```
oil_library/factory.py:103: in get_oil
    raise ex
E   NoResultFound: Oil with identifier "ALASKA NORTH SLOPE (MIDDLE PIPELINE)", not found in database.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================== 1 error in 0.89 seconds ===========
```

None of this seems however to cause any problems(?)

**Comment by JamesMakela-NOAA** [comment]
We will probably need to audit to make sure, but yes, I would think this is an improvement.

The optimization warning happens because there is a set of sample oils that we initialize in memory when the module is imported, and one of these records contains data that is a bit sparse for the curve_fit function.  It is just a warning, and does not affect any of the 'real' records in the database.

The pytest failure is happening because the name of the Alaska North Slope record has changed slightly.  I will fix this shortly, but it does not indicate any immediate problems with the module.

I think I will close this issue for now.  Thanks for your patience.
