### ISSUE TITLE
Two oils named JP-8

### ISSUE THREAD

**Issue by knutfrode** [NOAA-ORR-ERD/OilLibrary#5]
There seem to be two rows with oils named "JP-8":
https://github.com/NOAA-ORR-ERD/OilLibrary/blob/master/oil_library/OilLib#L661

```
get_oil_props('JP-8')
```
gives 
```
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()
```

**Comment by ChrisBarker-NOAA** [comment]
Indeed there are -- b ut they are not the same record. As I think about it, I don't think there is any guarantee that names will be unique -- we have an "ADIOS ID" field for that. But teh get_oil API does not give you any other way to get an oil!

I'm working on a few querying examples and a utility or two that will help, but we should probably de-duplicate that name in the DB as well.

Stay tuned

**Comment by JamesMakela-NOAA** [comment]
@knutfrode, @ChrisBarker-NOAA:

Yes, previously there was a unique constraint on the oil names in the database, but we modified it recently to be a unique constraint on (oil_name, location, field_name), so that you can have oils of the same name as long as they are from a different location.

This is not yet pushed to GitHub, but we now have an internal version of OilLibrary that is stable.  So you can expect a new tagged version of OilLibrary very, very soon.

**Comment by ChrisBarker-NOAA** [comment]
fixed -- at this point, names are not guaranteed to be unique -- but each recored has a unique "ADIOS ID".

The APIs should return multiple responses, or a reasonable error message if there are duplicates.
