### ISSUE TITLE
Problems installing NOAA

### ISSUE THREAD

**Issue by zepgago** [NOAA-ORR-ERD/OilLibrary#7]
Something obviously went wrong with the database. If anyone could help me I would appreciate:

![image](https://user-images.githubusercontent.com/29962199/27934367-47b64b00-629d-11e7-9fb1-873b53a3b27b.png)

**Comment by ChrisBarker-NOAA** [comment]
@JamesMakela-NOAA:

Has this been tested recently on Windows?

**Comment by ChrisBarker-NOAA** [comment]
This is working for us on Windows, but we may have identified the problem.

The setup.py is designed to install the oil_Library pacakge, an then build teh DB by running a script that was installed with the package.

The error you see indicates that it isn't finding that script, which means that the package install failed, or, more likely, that the Python package dir is not on your PATH.

How did you install Python? and how are you running this?

i.e. if you did a miniconda install, it will optionally add it to your PATH. If you didn't select that, then you need to run python from a "Anaconda cmd shell" (or something like that), rather than a plain cmd window shell, as a plain cmd Window will not have the PATH set correctly.

**Comment by zepgago** [comment]
Yes I installed miniconda 2 after installing python 2. 
Pasted everything that was inside the folder OilLibrary-master in the directory C:/Programs/Miniconda2.
I opened the windows Command Prompt, changed the directory to C:/Programs/Miniconda2 and then ran the following: python setup.py install

I'm trying to install the Oil Library in order to run the Opendrift software.

Sorry if I'm not able to do something easy, but I'm not an expert in programing and never tried python before.

Thank you for your cooperation @ChrisBarker-NOAA 
All the best

**Comment by zepgago** [comment]
If I run the same command in the Anaconda Prompt I get the following:
![image](https://user-images.githubusercontent.com/29962199/28126163-9af64e3c-6720-11e7-87d7-5ae5e2a06ae6.png)

**Comment by ChrisBarker-NOAA** [comment]
Ah:

"Yes I installed miniconda 2 after installing python 2."

miniconda 2 provides python itself. So you want to either use python installed separately or use miniconda, but not both.

If you want to use it with OpenDrift, you should install it and its dependencies the same way are doing OpenDrift.

Your current error is a dependency problem. you need to do one of:

for conda:

conda config --add channels conda-forge
conda install --file conda_requirements.txt

for non-conda python:

pip install -r requirements.txt

Then run setup.py install.

The setup.py does expect that the Python scripts dir is on PATH. Depending on how you installed Python it may or may not be.

-CHB

**Comment by zepgago** [comment]
@ChrisBarker-NOAA thanks a lot for your help!
All working well now!

I uninstalled both python and miniconda and installed miniconda2 again.

I still had to install some packages I had missing that I found in OilLibrary/oil_library_conda_recipe/meta.yaml

  >>conda install --yes numpy setuptools sqlalchemy transaction zope.sqlalchemy awesome-slugify unit_conversion pytest

And after that all went smoothly!

Cheers
